AffiliateProfile/Controllers/AffiliateSellController.cs
using AutoMapper;
using AffiliateProfile.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Repository.InterFace;
using System;
using System.Collections.Generic;
using Common.Extensions;

namespace AffiliateProfile.Controllers
{
    [Authorize(Roles = "Affiliate")]
    public class AffiliateSellController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _uow;

        public AffiliateSellController(IMapper mapper, IUnitOfWork uow)
        {
            _mapper = mapper;
            _uow = uow;
        }
        public IActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// show list view in View as Datatable jquery
        /// </summary>
        /// <returns></returns>

        public IActionResult List()
        {
            try
            {
                var dtValues = SetDataTableRequest();
                int recordsTotal = 0;
                var data = _mapper.Map<List<SellDto>>(_uow.SellRepo.Filter(dtValues.draw,
                    dtValues.length,
                    dtValues.sortColumn,
                    dtValues.sortColumnDirection,
                    dtValues.searchValue,
                    dtValues.pageSize,
                    dtValues.skip,
                    ref recordsTotal,
                    UserExtention.GetUserMail(User)));

                dtValues.recordsTotal = recordsTotal;

                return Json(new AjaxResult { draw = dtValues.draw, recordsFiltered = dtValues.recordsTotal, recordsTotal = dtValues.recordsTotal, data = data });
            }
            catch (Exception ex)
            {
                return Json("error");
            }
            
        }

    }

}

AffiliateProfile/Controllers/CustomersController.cs
using AutoMapper;
using AffiliateProfile.Models;
using Common.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Repository.InterFace;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace AffiliateProfile.Controllers
{
    [Authorize(Roles = "Affiliate")]
    public class CustomersController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _uow;

        public CustomersController(IMapper mapper, IUnitOfWork uow)
        {
            _mapper = mapper;
            _uow = uow;
        }
        public IActionResult Index()
        {
            return View();
        }
        //// <summary>
        /// show list view in View as Datatable jquery
        /// </summary>
        /// <returns></returns>

        public IActionResult List()
        {
            try
            {
                var dtValues = SetDataTableRequest();
                int recordsTotal = 0;
                var data = _uow.SellRepo.AffiliateCustomers(dtValues.draw,
                    dtValues.length,
                    dtValues.sortColumn,
                    dtValues.sortColumnDirection,
                    dtValues.searchValue,
                    dtValues.pageSize,
                    dtValues.skip,
                    ref recordsTotal,
                    UserExtention.GetUserMail(User));

                List<SellDto> list = new List<SellDto>();

                foreach (var email in data)
                {
                    var model = new SellDto()
                    {
                        Email = email
                    };
                    list.Add(model);
                }

                dtValues.recordsTotal = recordsTotal;

                return Json(new AjaxResult { draw = dtValues.draw, recordsFiltered = dtValues.recordsTotal, recordsTotal = dtValues.recordsTotal, data = list });
            }
            catch (Exception ex)
            {
                return Json("error");
            }
            
        }

    }

}

AffiliateProfile/Controllers/ReportController.cs
using AffiliateProfile.Models;
using AutoMapper;
using Common.Extensions;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Repository.InterFace;
using Stimulsoft.Report;
using Stimulsoft.Report.Engine;
using Stimulsoft.Report.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace AffiliateProfile.Controllers
{
    [Authorize(Roles = "Affiliate")]
    public class ReportController : BaseController
    {

        private readonly IMapper _mapper;
        private readonly IUnitOfWork _uow;

        public ReportController(IMapper mapper, IUnitOfWork uow)
        {
            _mapper = mapper;
            _uow = uow;
        }

        /// <summary>
        /// get report filter
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>

        public IActionResult AffiliateSellPrintPage(SellReportDto model)
        {
            TempData["StartDate"] = model.StartDate;
            TempData["EndDate"] = model.EndDate;
            TempData["FilterType"] = model.FilterType;
            TempData["SkipDate"] = model.SkipDate;

            return View();
        }


        public IActionResult ConversionRatePrintPage()
        {
            return View();
        }

        /// <summary>
        /// get affiliate sell for report
        /// </summary>
        /// <returns></returns>
        public ActionResult AffiliateSell()
        {
            try
            {
                var model = new SellReportDto();

                if (TempData["StartDate"] != null)
                {
                    model.StartDate = DateTime.Parse(TempData["StartDate"].ToString());
                }
                if (TempData["EndDate"] != null)
                {
                    model.EndDate = DateTime.Parse(TempData["EndDate"].ToString());
                }
                if(TempData["FilterType"] != null)
                {
                    model.FilterType = (FilterType)(TempData["FilterType"]);
                }
                if(TempData["SkipDate"] != null)
                {
                    model.SkipDate = (bool)(TempData["SkipDate"]);
                }

                StiReport stiReport = new StiReport();

                stiReport.Load(StiNetCoreHelper.MapPath(this, "wwwroot/Reports/AffiliateSellReport.mrt"));

                var affiliates = _uow.AffiliateRepo.Get(d => d.Email == UserExtention.GetUserMail(User)).FirstOrDefault();

                IEnumerable<Tb_Sell> sellRepo = null;
                switch (model.FilterType)
                {
                    case FilterType.All:
                        sellRepo = !model.SkipDate ? _uow.SellRepo.Get(d => d.AffiliateCode == affiliates.Code && d.CreateAt >= model.StartDate && d.CreateAt <= model.EndDate) : _uow.SellRepo.Get(d => d.AffiliateCode == affiliates.Code);
                        break;
                    case FilterType.OnlyRegister:
                        sellRepo = !model.SkipDate ? _uow.SellRepo.Get(d => d.AffiliateCode == affiliates.Code && d.PayStatus == PayStatus.Registered && d.CreateAt >= model.StartDate && d.CreateAt <= model.EndDate) : _uow.SellRepo.Get(d => d.AffiliateCode == affiliates.Code && d.PayStatus == PayStatus.Registered);
                        break;
                    case FilterType.Sells:
                        sellRepo = !model.SkipDate ? _uow.SellRepo.Get(d => d.AffiliateCode == affiliates.Code && d.PayStatus != PayStatus.Registered && d.CreateAt >= model.StartDate && d.CreateAt <= model.EndDate) : _uow.SellRepo.Get(d => d.AffiliateCode == affiliates.Code && d.PayStatus != PayStatus.Registered);
                        break;
                    default:

                        break;
                }

                var sumSell = sellRepo.Sum(d => d.Price);

                stiReport["SumSell"] = sumSell.ToString("N0");

                stiReport.RegData("affiliateDT", sellRepo);

                return StiNetCoreViewer.GetReportResult(this, stiReport);
            }
            catch (Exception ex)
            {
                return null;
            }


        }

        /// <summary>
        /// get affiliate ConversionRate as Pie Chart for report
        /// </summary>
        /// <returns></returns>
        public ActionResult ConversionRate()
        {
            StiReport stiReport = new StiReport();

            stiReport.Load(StiNetCoreHelper.MapPath(this, "wwwroot/Reports/ConversionRateReport.mrt"));

            var affiliates = _uow.AffiliateRepo.Get(d => d.Email == UserExtention.GetUserMail(User)).FirstOrDefault();
            var registeredSells = _uow.SellRepo.Get(d => d.AffiliateCode == affiliates.Code && d.PayStatus == PayStatus.Registered);
            stiReport["RegisteredSell"] = registeredSells != null ? registeredSells.Sum(d => d.Price) : 0;
            var AllSells = _uow.SellRepo.Get(d => d.AffiliateCode == affiliates.Code && d.PayStatus != PayStatus.Registered);
            stiReport["AllSellValue"] = AllSells != null ? AllSells.Sum(d => d.Price) : 0;

            return StiNetCoreViewer.GetReportResult(this, stiReport);

        }

        public IActionResult FilterAffiliateSell()
        {
            return View();
        }

        /// <summary>
        /// for display report views
        /// </summary>
        /// <returns></returns>
        public IActionResult ViewerEvent()
        {
            return StiNetCoreViewer.ViewerEventResult(this);
        }
    }
}

AffiliateProfile/Views/Shared/P_Header.cshtml
<nav class="navbar top-navbar col-lg-12 col-12 p-0">
    <div class="container">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
            <a class="navbar-brand brand-logo" href="index.html"><img src="~/images/logo-dark.svg" alt="logo" /></a>
            <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/images/logo-mini.svg" alt="logo" /></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
            
            <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item count-indicator nav-profile dropdown">
                    @*<span class="count">3</span>*@
                    <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                        <span class="nav-profile-name">Hi, @User.Identity.Name</span>
                        @{
                            var image = TempData["Image"] as string;
                            if (image != null)
                            {
                                if (image.Length > 0)
                                {
                                    <img class="rounded-circle header-profile-user" src="~/UserProfile/@image" alt="Header Avatar">
                                }
                                else
                                {
                                    <img class="rounded-circle header-profile-user" src="~/Admin/assets/images/users/avatar-1.jpg" alt="Header Avatar">
                                }
                            }
                            else
                            {
                                var images = User.Claims.FirstOrDefault(d => d.Type == "Image");
                                if (images.Value != "")
                                {
                                    <img class="rounded-circle header-profile-user" src="~/UserProfile/@images.Value" alt="Header Avatar">
                                }
                                else
                                {
                                    <img src="https://via.placeholder.com/36x36" alt="profile" />
                                }
                            }
                        }
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                        <a class="dropdown-item text-primary"  asp-action="Profile" asp-controller="Home">
                            <i class="mdi mdi-account-circle"></i>
                            Profile
                        </a>
                        <a class="dropdown-item text-primary" asp-action="ResetPassword" asp-controller="Account">
                            <i class="mdi mdi-repeat-once text-primary"></i>
                            Reset Password
                        </a>
                         <a class="dropdown-item text-primary" asp-action="LogOut" asp-controller="Account">
                            <i class="mdi mdi-logout text-primary"></i>
                            Log out
                        </a>

                    </div>
                </li>
                
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="horizontal-menu-toggle">
                <span class="mdi mdi-menu"></span>
            </button>
        </div>
    </div>
</nav>

AffiliateProfile/Views/Shared/P_TopMenu.cshtml
<nav class="bottom-navbar">
    <div class="container">
        <ul class="nav page-navigation">
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Home">
                    <i class="mdi mdi-view-dashboard-outline menu-icon"></i>
                    <span class="menu-title">Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="AffiliateSell">
                    <i class="mdi mdi-airplay menu-icon"></i>
                    <span class="menu-title">Lead/Sales</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Customers">
                    <i class="mdi mdi-account-multiple menu-icon"></i>
                    <span class="menu-title">My Customers</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="mdi mdi-printer menu-icon"></i>
                    <span class="menu-title">Reports</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="submenu">
                    <ul class="submenu-item">
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="add-ajax-modal" href="javascript:void(0);" data-url="@Url.Action("FilterAffiliateSell","Report")">
                                <i class="mdi mdi-printer menu-icon"></i>
                                <span class="menu-title">Affiliate Sell</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="ConversionRatePrintPage" target="_blank" asp-controller="Report">
                                <i class="mdi mdi-printer menu-icon"></i>
                                <span class="menu-title">Conversion Rate</span>
                            </a>
                        </li>

                    </ul>
                </div>
            </li>            
            @*<li class="nav-item">
                <a asp-action="Index" asp-controller="Offers" class="nav-link">
                    <i class="mdi mdi-file-document-box-outline menu-icon"></i>
                    <span class="menu-title">Offers</span>
                </a>
            </li>*@
        </ul>
    </div>
</nav>

AffiliateProfile/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Affiliate Profile</title>
    <link rel="stylesheet" href="~/Affiliate/vendors/mdi/css/materialdesignicons.min.css">

    <link rel="stylesheet" href="~/Affiliate/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/css/horizontal-layout-light/style.css">
    <link rel="shortcut icon" href="~/images/favicon.png" />

    @RenderSection("Styles", required: false)
    <script src="~/Affiliate/vendors/js/vendor.bundle.base.js"></script>
</head>


<body>
    <div id="modal-placeholder"></div>
    <div class="container-scroller">
        <div class="horizontal-menu">
            <partial name="P_Header" />
            <partial name="P_TopMenu" />
        </div>
        <div class="container-fluid page-body-wrapper">
            <div class="main-panel">
                @RenderBody()
                @*<div class="footer"></div>*@
            </div>
        </div>
    </div>
    <script src="~/Affiliate/vendors/chart.js/Chart.min.js"></script>
    <script src="~/js/hoverable-collapse.js"></script>
    <script src="~/js/template.js"></script>
    <script src="~/js/dashboard.js"></script>
    <script src="~/js/Ajax.js"></script>
    <script src="~/Affiliate/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/js/formpickers.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>